site_name: Peterborough Chess Club
site_url: https://peterboroughchessclub.github.io/site/
site_author: Doug Redden

# Repository
repo_name: peterboroughchessclub/peterboroughchessclub
repo_url: https://github.com/peterboroughchessclub/site

# Customization
extra_css: [templates_overrides/extra.css]

theme:
    name: material
    custom_dir: docs/templates_overrides    
    palette:
      - scheme: default
        primary: stylesheets/extra.css
        accent: indigo
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: blue grey
        accent: indigo
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

    font:
      text: Roboto
      code: Roboto Mono
    favicon: assets/favicon.png
    icon:
      logo: material/chess-queen

    features:
      # - announce.dismiss
      - content.action.edit
      - content.action.view
      - content.code.annotate
      - content.code.copy
      # - content.code.select
      - content.tabs.link
      - content.tooltips
      # - header.autohide
      # - navigation.expand
      - navigation.footer
      # - navigation.indexes
      - navigation.instant
      - navigation.path
      # - navigation.prune
      - navigation.sections
      - navigation.tabs
      # - navigation.tabs.sticky
      - navigation.top
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      - toc.follow
      - toc.integrate


markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
# Plugins
plugins:
  - macros
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - minify:
  #     minify_html: true
  - mkdocs-pdf


# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/peterboroughchessclub
    - icon: fontawesome/brands/facebook 
      link: www.facebook.com/peterboroughchessclub/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/peterboroughchessclub
nav:
    - Introduction: index.md
    - Gallery: gallery.md
    - Latest News: news.md
    - Keith Arkell Simultaneous Exhibition: KeithAskellSimultaneousExhibition.md
    - Silver Queen: SilverQueen11September2025.md
    - Competitions: competitions.md
    - History: history.md
    - Tuition: tutorials.md
    - CAMBS ICC 24: CAMBS_INDIVIDUAL_CHESS_CHAMPIONSHIP_2024.md
    - Submit pgn: submitpgn.md
    - Game of the week: GameOfTheWeek.md
    # - Software skills: websiteDevelopmentIdeas.md
    - Contact us: contactus.md
  

  # - search:
  #     separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - markdown-exec:
  #       exec: true
  # - gen-files:
  #     scripts:
  #       - docs/gen_pages.py       

  # - gallery:
  #     examples_dirs: docs/examples          # path to your example scripts
  #     gallery_dirs: docs/generated/gallery  # where to save generated gallery
  #     backreferences_dir: docs/generated/backreferences # where to generate the back references summary
      # image_scrapers: [] # which image scrapers to use
      # compress_images: ['images', 'thumbnails'] # which images to compress
      # within_subsection_order: FileNameSortKey # specify the order of examples to be according to filename

      # doc_module: ['mkdocs_gallery'] # modules to document
 
  # - minify:
  #     minify_html: true





